language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  chrome: stable
branches:
  only:
    - gh-pages
    - /.*/
services:
  - docker

before_install:
  - docker pull eclipse-mosquitto
  - docker run -d -p 9001:9001 -v $(pwd)/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro eclipse-mosquitto
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  - npm install -g @angular/cli
  - npm install codecov -g
script:
  - ng lint
  - npm run test-headless
  - docker build .
scripts:

after_success:
  - codecov
